project:
  type: website
  output-dir: docs

website:
  title: "New Projects"
  navbar:
    right:
      - href: index.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

react:
  components: _components
  resources: _components

execute:
  freeze: auto

